name: Build

on: push

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup SDL2
        run: |
          vcpkg install sdl2:x64-windows

  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup SDL2
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Setup chksum64 and bass
        run: |
          mkdir -p tmp
          cd tmp
          wget https://raw.githubusercontent.com/DragonMinded/libdragon/trunk/tools/chksum64.c
          gcc chksum64.c -o chksum64
          sudo mv chksum64 /bin/
          git clone https://github.com/ARM9/bass.git
          cd bass/bass
          make
          sudo mv bass /bin/

      - name: Build N64
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          strip n64

      - name: Run tests on N64
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cd build
          make test

      - name: Collect files
        run: |
          mkdir upload
          mv build/n64 upload

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: n64-linux
          path: upload
