use dgbir::ir::{IRContext, IRFunction};

use crate::mips_parser::{BranchInfo, MipsOpcode, ParsedMipsInstruction};

pub fn to_ir(parsed: Vec<ParsedMipsInstruction>) {
    let context = IRContext::new();
    let func = IRFunction::new(context);


    for instr in parsed {
        let iw = instr.instr.raw();
        let op_enum = instr.op;
        let vaddr = instr.vaddr;
        let paddr = instr.paddr;
        println!("{vaddr:016X}\t{paddr:08X}\t{iw:08X} (opcode {op_enum:?})");

        match op_enum {
            MipsOpcode::NOP => todo!("NOP"),
            MipsOpcode::LD => todo!("LD"),
            MipsOpcode::LUI => todo!("LUI"),
            MipsOpcode::ADDI => todo!("ADDI"),
            MipsOpcode::ADDIU => todo!("ADDIU"),
            MipsOpcode::DADDI => todo!("DADDI"),
            MipsOpcode::ANDI => todo!("ANDI"),
            MipsOpcode::LBU => todo!("LBU"),
            MipsOpcode::LHU => todo!("LHU"),
            MipsOpcode::LH => todo!("LH"),
            MipsOpcode::LW => todo!("LW"),
            MipsOpcode::LWU => todo!("LWU"),
            MipsOpcode::BRANCH(BranchInfo { cond: _cond, likely: _likely, link: _link }) => todo!("BRANCH"),
            MipsOpcode::CACHE => todo!("CACHE"),
            MipsOpcode::SB => todo!("SB"),
            MipsOpcode::SH => todo!("SH"),
            MipsOpcode::SD => todo!("SD"),
            MipsOpcode::SW => todo!("SW"),
            MipsOpcode::ORI => todo!("ORI"),
            MipsOpcode::J => todo!("J"),
            MipsOpcode::JAL => todo!("JAL"),
            MipsOpcode::SLTI => todo!("SLTI"),
            MipsOpcode::SLTIU => todo!("SLTIU"),
            MipsOpcode::XORI => todo!("XORI"),
            MipsOpcode::DADDIU => todo!("DADDIU"),
            MipsOpcode::LB => todo!("LB"),
            MipsOpcode::LDC1 => todo!("LDC1"),
            MipsOpcode::SDC1 => todo!("SDC1"),
            MipsOpcode::LWC1 => todo!("LWC1"),
            MipsOpcode::SWC1 => todo!("SWC1"),
            MipsOpcode::LWL => todo!("LWL"),
            MipsOpcode::LWR => todo!("LWR"),
            MipsOpcode::SWL => todo!("SWL"),
            MipsOpcode::SWR => todo!("SWR"),
            MipsOpcode::LDL => todo!("LDL"),
            MipsOpcode::LDR => todo!("LDR"),
            MipsOpcode::SDL => todo!("SDL"),
            MipsOpcode::SDR => todo!("SDR"),
            MipsOpcode::LL => todo!("LL"),
            MipsOpcode::LLD => todo!("LLD"),
            MipsOpcode::SC => todo!("SC"),
            MipsOpcode::SCD => todo!("SCD"),
            MipsOpcode::RDHWR => todo!("RDHWR"),
            MipsOpcode::MFC0 => todo!("MFC0"),
            MipsOpcode::DMFC0 => todo!("DMFC0"),
            MipsOpcode::CFC0 => todo!("CFC0"),
            MipsOpcode::DCFC0 => todo!("DCFC0"),
            MipsOpcode::MTC0 => todo!("MTC0"),
            MipsOpcode::DMTC0 => todo!("DMTC0"),
            MipsOpcode::CTC0 => todo!("CTC0"),
            MipsOpcode::DCTC0 => todo!("DCTC0"),
            MipsOpcode::MFC1 => todo!("MFC1"),
            MipsOpcode::DMFC1 => todo!("DMFC1"),
            MipsOpcode::CFC1 => todo!("CFC1"),
            MipsOpcode::DCFC1 => todo!("DCFC1"),
            MipsOpcode::MTC1 => todo!("MTC1"),
            MipsOpcode::DMTC1 => todo!("DMTC1"),
            MipsOpcode::CTC1 => todo!("CTC1"),
            MipsOpcode::DCTC1 => todo!("DCTC1"),
            MipsOpcode::SLL => todo!("SLL"),
            MipsOpcode::SRL => todo!("SRL"),
            MipsOpcode::SRA => todo!("SRA"),
            MipsOpcode::SRAV => todo!("SRAV"),
            MipsOpcode::SLLV => todo!("SLLV"),
            MipsOpcode::SRLV => todo!("SRLV"),
            MipsOpcode::JR => todo!("JR"),
            MipsOpcode::JALR => todo!("JALR"),
            MipsOpcode::SYSCALL => todo!("SYSCALL"),
            MipsOpcode::SYNC => todo!("SYNC"),
            MipsOpcode::MFHI => todo!("MFHI"),
            MipsOpcode::MTHI => todo!("MTHI"),
            MipsOpcode::MFLO => todo!("MFLO"),
            MipsOpcode::MTLO => todo!("MTLO"),
            MipsOpcode::DSLLV => todo!("DSLLV"),
            MipsOpcode::DSRLV => todo!("DSRLV"),
            MipsOpcode::DSRAV => todo!("DSRAV"),
            MipsOpcode::MULT => todo!("MULT"),
            MipsOpcode::MULTU => todo!("MULTU"),
            MipsOpcode::DIV => todo!("DIV"),
            MipsOpcode::DIVU => todo!("DIVU"),
            MipsOpcode::DMULT => todo!("DMULT"),
            MipsOpcode::DMULTU => todo!("DMULTU"),
            MipsOpcode::DDIV => todo!("DDIV"),
            MipsOpcode::DDIVU => todo!("DDIVU"),
            MipsOpcode::ADD => todo!("ADD"),
            MipsOpcode::ADDU => todo!("ADDU"),
            MipsOpcode::AND => todo!("AND"),
            MipsOpcode::SUB => todo!("SUB"),
            MipsOpcode::SUBU => todo!("SUBU"),
            MipsOpcode::OR => todo!("OR"),
            MipsOpcode::XOR => todo!("XOR"),
            MipsOpcode::NOR => todo!("NOR"),
            MipsOpcode::SLT => todo!("SLT"),
            MipsOpcode::SLTU => todo!("SLTU"),
            MipsOpcode::DADD => todo!("DADD"),
            MipsOpcode::DADDU => todo!("DADDU"),
            MipsOpcode::DSUB => todo!("DSUB"),
            MipsOpcode::DSUBU => todo!("DSUBU"),
            MipsOpcode::TGE => todo!("TGE"),
            MipsOpcode::TGEU => todo!("TGEU"),
            MipsOpcode::TLT => todo!("TLT"),
            MipsOpcode::TLTU => todo!("TLTU"),
            MipsOpcode::TEQ => todo!("TEQ"),
            MipsOpcode::TNE => todo!("TNE"),
            MipsOpcode::DSLL => todo!("DSLL"),
            MipsOpcode::DSRL => todo!("DSRL"),
            MipsOpcode::DSRA => todo!("DSRA"),
            MipsOpcode::DSLL32 => todo!("DSLL32"),
            MipsOpcode::DSRL32 => todo!("DSRL32"),
            MipsOpcode::DSRA32 => todo!("DSRA32"),
        }

    }
}
