use dgbir::ir::{IRContext, IRFunction};

use crate::mips_parser::{BranchInfo, MipsOpcode, ParsedMipsInstruction};

pub fn to_ir(parsed: Vec<ParsedMipsInstruction>) {
    let context = IRContext::new();
    let func = IRFunction::new(context);


    for instr in parsed {
        let iw = instr.instr.raw();
        let op_enum = instr.op;
        let vaddr = instr.vaddr;
        let paddr = instr.paddr;
        println!("{vaddr:016X}\t{paddr:08X}\t{iw:08X} (opcode {op_enum:?})");

        match op_enum {
            MipsOpcode::NOP => todo!(),
            MipsOpcode::LD => todo!(),
            MipsOpcode::LUI => todo!(),
            MipsOpcode::ADDI => todo!(),
            MipsOpcode::ADDIU => todo!(),
            MipsOpcode::DADDI => todo!(),
            MipsOpcode::ANDI => todo!(),
            MipsOpcode::LBU => todo!(),
            MipsOpcode::LHU => todo!(),
            MipsOpcode::LH => todo!(),
            MipsOpcode::LW => todo!(),
            MipsOpcode::LWU => todo!(),
            MipsOpcode::BRANCH(BranchInfo { cond: _cond, likely: _likely, link: _link }) => todo!(),
            MipsOpcode::CACHE => todo!(),
            MipsOpcode::SB => todo!(),
            MipsOpcode::SH => todo!(),
            MipsOpcode::SD => todo!(),
            MipsOpcode::SW => todo!(),
            MipsOpcode::ORI => todo!(),
            MipsOpcode::J => todo!(),
            MipsOpcode::JAL => todo!(),
            MipsOpcode::SLTI => todo!(),
            MipsOpcode::SLTIU => todo!(),
            MipsOpcode::XORI => todo!(),
            MipsOpcode::DADDIU => todo!(),
            MipsOpcode::LB => todo!(),
            MipsOpcode::LDC1 => todo!(),
            MipsOpcode::SDC1 => todo!(),
            MipsOpcode::LWC1 => todo!(),
            MipsOpcode::SWC1 => todo!(),
            MipsOpcode::LWL => todo!(),
            MipsOpcode::LWR => todo!(),
            MipsOpcode::SWL => todo!(),
            MipsOpcode::SWR => todo!(),
            MipsOpcode::LDL => todo!(),
            MipsOpcode::LDR => todo!(),
            MipsOpcode::SDL => todo!(),
            MipsOpcode::SDR => todo!(),
            MipsOpcode::LL => todo!(),
            MipsOpcode::LLD => todo!(),
            MipsOpcode::SC => todo!(),
            MipsOpcode::SCD => todo!(),
            MipsOpcode::RDHWR => todo!(),
            MipsOpcode::MFC0 => todo!(),
            MipsOpcode::DMFC0 => todo!(),
            MipsOpcode::CFC0 => todo!(),
            MipsOpcode::DCFC0 => todo!(),
            MipsOpcode::MTC0 => todo!(),
            MipsOpcode::DMTC0 => todo!(),
            MipsOpcode::CTC0 => todo!(),
            MipsOpcode::DCTC0 => todo!(),
            MipsOpcode::MFC1 => todo!(),
            MipsOpcode::DMFC1 => todo!(),
            MipsOpcode::CFC1 => todo!(),
            MipsOpcode::DCFC1 => todo!(),
            MipsOpcode::MTC1 => todo!(),
            MipsOpcode::DMTC1 => todo!(),
            MipsOpcode::CTC1 => todo!(),
            MipsOpcode::DCTC1 => todo!(),
            MipsOpcode::SLL => todo!(),
            MipsOpcode::SRL => todo!(),
            MipsOpcode::SRA => todo!(),
            MipsOpcode::SRAV => todo!(),
            MipsOpcode::SLLV => todo!(),
            MipsOpcode::SRLV => todo!(),
            MipsOpcode::JR => todo!(),
            MipsOpcode::JALR => todo!(),
            MipsOpcode::SYSCALL => todo!(),
            MipsOpcode::SYNC => todo!(),
            MipsOpcode::MFHI => todo!(),
            MipsOpcode::MTHI => todo!(),
            MipsOpcode::MFLO => todo!(),
            MipsOpcode::MTLO => todo!(),
            MipsOpcode::DSLLV => todo!(),
            MipsOpcode::DSRLV => todo!(),
            MipsOpcode::DSRAV => todo!(),
            MipsOpcode::MULT => todo!(),
            MipsOpcode::MULTU => todo!(),
            MipsOpcode::DIV => todo!(),
            MipsOpcode::DIVU => todo!(),
            MipsOpcode::DMULT => todo!(),
            MipsOpcode::DMULTU => todo!(),
            MipsOpcode::DDIV => todo!(),
            MipsOpcode::DDIVU => todo!(),
            MipsOpcode::ADD => todo!(),
            MipsOpcode::ADDU => todo!(),
            MipsOpcode::AND => todo!(),
            MipsOpcode::SUB => todo!(),
            MipsOpcode::SUBU => todo!(),
            MipsOpcode::OR => todo!(),
            MipsOpcode::XOR => todo!(),
            MipsOpcode::NOR => todo!(),
            MipsOpcode::SLT => todo!(),
            MipsOpcode::SLTU => todo!(),
            MipsOpcode::DADD => todo!(),
            MipsOpcode::DADDU => todo!(),
            MipsOpcode::DSUB => todo!(),
            MipsOpcode::DSUBU => todo!(),
            MipsOpcode::TGE => todo!(),
            MipsOpcode::TGEU => todo!(),
            MipsOpcode::TLT => todo!(),
            MipsOpcode::TLTU => todo!(),
            MipsOpcode::TEQ => todo!(),
            MipsOpcode::TNE => todo!(),
            MipsOpcode::DSLL => todo!(),
            MipsOpcode::DSRL => todo!(),
            MipsOpcode::DSRA => todo!(),
            MipsOpcode::DSLL32 => todo!(),
            MipsOpcode::DSRL32 => todo!(),
            MipsOpcode::DSRA32 => todo!(),
        }

    }
}
