[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
proc-bitfield = "0.5.0"
itertools = "0.13.0"
dgbir = { path = "./dgbir" }

[build-dependencies]
bindgen = "0.71.1"
