[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[features]
default = []
ir_comments = ["dgbir/ir_comments"]

[lib]
crate-type = ["staticlib", "rlib"] # staticlib = for emulator, rlib = so integration tests still work

[dependencies]
capstone = "0.14.0"
proc-bitfield = "0.5.2"
itertools = "0.15.0"
dgbir = { path = "./dgbir" }
log = "0.4.28"
env_logger = "0.11.8"
derive_builder = "0.20.2"

[build-dependencies]
bindgen = "0.72.1"
